image: Visual Studio 2015 # образ для сборки
stack: node 10 # окружение
branches:
only:
  - master # ветка git
cache: node_modules # кешировани
install:
  - npm install # команда установки зависимостей
build: off
test_script:
  - npm run lint && npm test # скрипт сборки